<?php
declare(strict_types=1);

// Autoscrape SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

AutoscrapeUtility::setRegistrar(function (AutoscrapeUtility $u): void {
    $u->clean = [AutoscrapeClean::class, 'call'];
    $u->done = [AutoscrapeDone::class, 'call'];
    $u->make_error = [AutoscrapeMakeError::class, 'call'];
    $u->feature_add = [AutoscrapeFeatureAdd::class, 'call'];
    $u->feature_hook = [AutoscrapeFeatureHook::class, 'call'];
    $u->feature_init = [AutoscrapeFeatureInit::class, 'call'];
    $u->fetcher = [AutoscrapeFetcher::class, 'call'];
    $u->make_fetch_def = [AutoscrapeMakeFetchDef::class, 'call'];
    $u->make_context = [AutoscrapeMakeContext::class, 'call'];
    $u->make_options = [AutoscrapeMakeOptions::class, 'call'];
    $u->make_request = [AutoscrapeMakeRequest::class, 'call'];
    $u->make_response = [AutoscrapeMakeResponse::class, 'call'];
    $u->make_result = [AutoscrapeMakeResult::class, 'call'];
    $u->make_point = [AutoscrapeMakePoint::class, 'call'];
    $u->make_spec = [AutoscrapeMakeSpec::class, 'call'];
    $u->make_url = [AutoscrapeMakeUrl::class, 'call'];
    $u->param = [AutoscrapeParam::class, 'call'];
    $u->prepare_auth = [AutoscrapePrepareAuth::class, 'call'];
    $u->prepare_body = [AutoscrapePrepareBody::class, 'call'];
    $u->prepare_headers = [AutoscrapePrepareHeaders::class, 'call'];
    $u->prepare_method = [AutoscrapePrepareMethod::class, 'call'];
    $u->prepare_params = [AutoscrapePrepareParams::class, 'call'];
    $u->prepare_path = [AutoscrapePreparePath::class, 'call'];
    $u->prepare_query = [AutoscrapePrepareQuery::class, 'call'];
    $u->graphql_body = [AutoscrapeGraphql::class, 'body'];
    $u->graphql_errors = [AutoscrapeGraphql::class, 'errors'];
    $u->result_basic = [AutoscrapeResultBasic::class, 'call'];
    $u->result_body = [AutoscrapeResultBody::class, 'call'];
    $u->result_headers = [AutoscrapeResultHeaders::class, 'call'];
    $u->transform_request = [AutoscrapeTransformRequest::class, 'call'];
    $u->transform_response = [AutoscrapeTransformResponse::class, 'call'];
});
